// Define static syllabus curriculum
export const SYLLABUS_DATA = {
  Final: {
    'Paper 1: Financial Reporting': [
      'Introduction to Indian Accounting Standards',
      'Conceptual Framework for Financial Reporting under Indian Accounting Standards (Ind AS)',
      'Ind AS 1 Presentation of Financial Statements',
      'Ind AS 34 Interim Financial Reporting',
      'Ind AS 7 Statement of Cash Flows',
      'Ind AS 8 Accounting Policies, Changes in Accounting Estimates and Errors',
      'Ind AS IO Events after the Reporting Period',
      'Ind AS 113 Fair Value Measurement',
      'Division II of Schedule III to the Companies Act, 2013',
      'Ind AS 2 Inventories',
      'Ind AS 16 Property, Plant and Equipment',
      'Ind AS 23 Borrowing Costs',
      'Ind AS 36 Impairment of Assets',
      'Ind AS 38 Intangible Assets',
      'Ind AS 40 Investment Property',
      'Ind AS 105 Non-current Assets Held for Sale and Discontinued Operations',
      'Ind AS 116 Leases',
      'Ind AS 19 Employee Benefits',
      'Ind AS 37 Provisions, Contingent Liabilities and Contingent Assets',
      'Ind AS 12 Income Taxes',
      'Ind AS 21 The Effects of Changes in Foreign Exchange Rates',
      'Ind AS 24 Related Party Disclosures',
      'Ind AS 33 Earnings per Share',
      'Ind AS 108 Operating Segments',
      'Ind AS 115 Revenue from Contracts with Customers',
      'Ind AS 41 Agriculture',
      'Ind AS 20 Accounting for Government Grants and Disclosure of Government Assistance',
      'Ind AS 102 Share Based Payment',
      'Accounting and Reporting of Financial Instruments',
      'Ind AS 103 Business Combinations',
      'Consolidated and Separate Financial Statements Of Group Entities',
      'Ind AS 101 First-time Adoption of Ind AS',
      'Analysis Of Financial Statements',
      'Professional and Ethical Duty of a Chartered Accountant',
      'Accounting and Technology'
    ],
    'Paper 2: Advanced Financial Management': [
      'Financial Policy and Corporate Strategy',
      'Risk Management',
      'Advanced Capital Budgeting Decision',
      'Security Analysis',
      'Security Valuation',
      'Portfolio Management',
      'Securitization',
      'Mutual Funds',
      'Derivatives Analysis and Valuation',
      'Foreign Exchange Exposure and Risk Management',
      'International Financial Management',
      'Interest Rate Risk Management',
      'Business Valuation',
      'Mergers, Acquisitions and Corporate Restructuring',
      'Startup Finance'
    ],
    'Paper 3: Advanced Auditing and Assurance': [
      'Quality Control',
      'General Auditing Principles and Auditors Responsibilities',
      'Audit Planning, Strategy and Execution',
      'Materiality, Risk Assessment and Internal Control',
      'Audit Evidence',
      'Completion and Review',
      'Reporting',
      'Specialised Areas',
      'Related Services',
      'Review of Financial Information',
      'Prospective Financial Information and Other Assurance Services',
      'Digital Auditing & Assurance',
      'Group Audits',
      'Special Features of Audit of Banks & Non-Banking Financial Companies',
      'Overview of Audit of Public Sector Undertakings',
      'Internal Audit',
      'Due Diligence, Investigation & Forensic Accountir',
      'Sustainable Development Goals (SDG) & Environment, Social and Governance (ESG) Assurance',
      'Professional Ethics & Liabilities of Auditors'
    ],
    'Paper 4: Direct Tax and International Taxation': [
      'Basic Concepts',
      'Incomes which do not form part of Total Income',
      'Profits and Gains Of Business or Profession',
      'Capital Gains',
      'Income from Other Sources',
      'Income of Other Persons included in Assessee\'s Total Income',
      'Aggregation of Income, Set Off or Carry Forward of Losses',
      'Deductions from Gross Total Income',
      'Assessment of Various Entities',
      'Assessment of Trusts and Institutions, Political Parties and Other Special Entities',
      'Tax Planning, Tax Avoidance and Tax Evasion',
      'Taxation Of Digital Transactions',
      'Deduction, Collection and Recovery of Tax',
      'Income Tax Authorities',
      'Assessment Procedure',
      'Appeals and Revision',
      'Dispute Resolution',
      'Miscellaneous Provisions',
      'Provisions to Counteract Unethical Tax Practices',
      'Tax Audit and Ethical Compliances',
      'Non Resident Taxation',
      'Double Taxation Relief',
      'Advance Rulings',
      'Transfer Pricing',
      'Fundamentals of BEPS',
      'Application and Interpretation of Tax Treaties',
      'Overview of Model Tax Conventions',
      'Latest Developments in International Taxation'
    ],
    'Paper 5: Indirect Taxation and Customs': [
      'Supply under GST',
      'Charge of GST',
      'Place of Supply',
      'Exemptions from GST',
      'Time of Supply',
      'Value of Supply',
      'Input Tax Credit',
      'Registration',
      'Tax Invoice, Credit and Debit Notes',
      'Accounts and Records; E-way Bill',
      'Payment Of Tax',
      'Electronic Commerce Transactions',
      'Returns',
      'Import and Export Under GST',
      'Refunds',
      'Job Work',
      'Assessment and Audit',
      'Inspection, Search, Seizure and Arrest',
      'Demands and Recovery',
      'Liability to Pay in Certain Cases',
      'Offences and Penalties and Ethical Aspects under GST',
      'Appeals and Revision',
      'Advance Ruling',
      'Miscellaneous Provisions',
      'Levy of and Exemptions from Customs Duty',
      'Types of Duty',
      'Classification of Imported and Export Goods',
      'Valuation under the Customs Act, 1962',
      'Importation and Exportation of Goods',
      'Warehousing',
      'Refund',
      'Foreign Trade Policy'
    ]
  },
  Intermediate: {
    'Advanced Accounting': [],
    'Corporate & Other Laws': [],
    'Taxation (DT & IDT)': [],
    'Cost & Management Accounting': []
  },
  Foundation: {
    'Principles & Practice of Accounting': [],
    'Business Laws': [],
    'Quantitative Aptitude': [],
    'Business Economics': []
  }
};
